In [1]:
from algorithm import *

In [2]:
a = 'GARFIELD_THE_LAST_FAT_CAT'
b = 'GARFIELD_THE_FAST_CAT'
c = 'GARFIELD_THE_VERY_FAST_CAT'
d = 'THE_FAT_CAT'

dictionary = set(a+b+c+d+'-'+'#')
len_dict = len(dictionary)

score_mat = np.zeros((len_dict, len_dict))
for i in range(len_dict):
    for j in range(len_dict):
        if i == j:
            score_mat[i, j] = 1
        else:
            score_mat[i, j] = -1
# gap_ind = np.where(np.array(list(dictionary)) == '-')[0]
# score_mat[gap_ind, gap_ind] = -1 # ?
msa = MSA(''.join(dictionary), score_mat)

In [3]:
D = msa.compute_D([a, b, c, d])
print(D)

[[0.         0.20189021 0.22643033 0.73678678]
 [0.20189021 0.         0.17913069 0.57214205]
 [0.22643033 0.17913069 0.         0.76200984]
 [0.73678678 0.57214205 0.76200984 0.        ]]


In [4]:
msa.build_guide_tree(D)

[3, [0, [1, 2]]]

In [5]:
alignment = msa.compute_msa([a, b, c, d])
for align in alignment:
    print(align)

#########THE_#####FA#T_CAT
GARFIELD_THE_LAST_FA#T_CAT
GARFIELD_THE_#####FAST_CAT
GARFIELD_THE_VERY_FAST_CAT
